services:
  - type: web
    name: estimador-viviendas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13


