services:
  - type: web
    name: estimador-de-viviendas
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn estimador_viviendas.wsgi:application --bind 0.0.0.0:8000


